name: Main workflow

on:
  pull_request:

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Setup Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install "poetry=1.3.2"
          poetry install

      - name: Run tests
        run: poetry run coverage run -m pytest

      - name: Update code coverage badge
        run: poetry run coverage-badge -o coverage.svg -f

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update code coverage badge
